// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/callUpload.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallUpload_CallUpload_FullMethodName = "/service.callUpload/callUpload"
)

// CallUploadClient is the client API for CallUpload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallUploadClient interface {
	CallUpload(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*ErrInfo, error)
}

type callUploadClient struct {
	cc grpc.ClientConnInterface
}

func NewCallUploadClient(cc grpc.ClientConnInterface) CallUploadClient {
	return &callUploadClient{cc}
}

func (c *callUploadClient) CallUpload(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*ErrInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrInfo)
	err := c.cc.Invoke(ctx, CallUpload_CallUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallUploadServer is the server API for CallUpload service.
// All implementations must embed UnimplementedCallUploadServer
// for forward compatibility.
type CallUploadServer interface {
	CallUpload(context.Context, *FileInfo) (*ErrInfo, error)
	mustEmbedUnimplementedCallUploadServer()
}

// UnimplementedCallUploadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallUploadServer struct{}

func (UnimplementedCallUploadServer) CallUpload(context.Context, *FileInfo) (*ErrInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallUpload not implemented")
}
func (UnimplementedCallUploadServer) mustEmbedUnimplementedCallUploadServer() {}
func (UnimplementedCallUploadServer) testEmbeddedByValue()                    {}

// UnsafeCallUploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallUploadServer will
// result in compilation errors.
type UnsafeCallUploadServer interface {
	mustEmbedUnimplementedCallUploadServer()
}

func RegisterCallUploadServer(s grpc.ServiceRegistrar, srv CallUploadServer) {
	// If the following call pancis, it indicates UnimplementedCallUploadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallUpload_ServiceDesc, srv)
}

func _CallUpload_CallUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallUploadServer).CallUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallUpload_CallUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallUploadServer).CallUpload(ctx, req.(*FileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// CallUpload_ServiceDesc is the grpc.ServiceDesc for CallUpload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallUpload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.callUpload",
	HandlerType: (*CallUploadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "callUpload",
			Handler:    _CallUpload_CallUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/callUpload.proto",
}
