// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/callUpload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileDataJson  []byte                 `protobuf:"bytes,1,opt,name=fileDataJson,proto3" json:"fileDataJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_callUpload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callUpload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_callUpload_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFileDataJson() []byte {
	if x != nil {
		return x.FileDataJson
	}
	return nil
}

type ErrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrStr        string                 `protobuf:"bytes,1,opt,name=errStr,proto3" json:"errStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrInfo) Reset() {
	*x = ErrInfo{}
	mi := &file_proto_callUpload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfo) ProtoMessage() {}

func (x *ErrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_callUpload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfo.ProtoReflect.Descriptor instead.
func (*ErrInfo) Descriptor() ([]byte, []int) {
	return file_proto_callUpload_proto_rawDescGZIP(), []int{1}
}

func (x *ErrInfo) GetErrStr() string {
	if x != nil {
		return x.ErrStr
	}
	return ""
}

var File_proto_callUpload_proto protoreflect.FileDescriptor

const file_proto_callUpload_proto_rawDesc = "" +
	"\n" +
	"\x16proto/callUpload.proto\x12\aservice\".\n" +
	"\bfileInfo\x12\"\n" +
	"\ffileDataJson\x18\x01 \x01(\fR\ffileDataJson\"!\n" +
	"\aerrInfo\x12\x16\n" +
	"\x06errStr\x18\x01 \x01(\tR\x06errStr2?\n" +
	"\n" +
	"callUpload\x121\n" +
	"\n" +
	"callUpload\x12\x11.service.fileInfo\x1a\x10.service.errInfoB\tZ\a./protob\x06proto3"

var (
	file_proto_callUpload_proto_rawDescOnce sync.Once
	file_proto_callUpload_proto_rawDescData []byte
)

func file_proto_callUpload_proto_rawDescGZIP() []byte {
	file_proto_callUpload_proto_rawDescOnce.Do(func() {
		file_proto_callUpload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_callUpload_proto_rawDesc), len(file_proto_callUpload_proto_rawDesc)))
	})
	return file_proto_callUpload_proto_rawDescData
}

var file_proto_callUpload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_callUpload_proto_goTypes = []any{
	(*FileInfo)(nil), // 0: service.fileInfo
	(*ErrInfo)(nil),  // 1: service.errInfo
}
var file_proto_callUpload_proto_depIdxs = []int32{
	0, // 0: service.callUpload.callUpload:input_type -> service.fileInfo
	1, // 1: service.callUpload.callUpload:output_type -> service.errInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_callUpload_proto_init() }
func file_proto_callUpload_proto_init() {
	if File_proto_callUpload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_callUpload_proto_rawDesc), len(file_proto_callUpload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_callUpload_proto_goTypes,
		DependencyIndexes: file_proto_callUpload_proto_depIdxs,
		MessageInfos:      file_proto_callUpload_proto_msgTypes,
	}.Build()
	File_proto_callUpload_proto = out.File
	file_proto_callUpload_proto_goTypes = nil
	file_proto_callUpload_proto_depIdxs = nil
}
